helper methods
defaultLibrary
	^ OrderedCollection withAll: #(
	'Somoeone stole your keys. Sorry about that.' 
	'Remember to breathe. :)' 
	'That guy is looking at you and it seems like he wants to fight?'
	'YOU FAILED THIS ASSIGNMENT'
	'That Starbucks barista? She hates your guts.'
	'Hungry? Have a SNICKERS!' 
	'Many quite distinguished people have bodies similar to yours.'
	'Its okay if you dont have a bedframe. Youre doing just fine.'
	'MAY EXPLODE IF IMPROPERLY RECHARGED'
	'Silica Gel Packet. DO NOT EAT'
	).